import { FMSData } from '@/types';

const fmsData: FMSData = {
  services_and_treatments: [
    {
      id: 'dental-implants',
      name: 'Dental Implants',
      category: 'Implants',
      tags: ['implants', 'restorative'],
      short_description: 'Permanent tooth replacement with titanium implants that look, feel, and function like natural teeth.',
      detailed_description: 'FMS Dental is a pioneer in dental implant surgery in Hyderabad, with over 20,000 successful implant procedures. Our implantologists use state-of-the-art 3D cone beam CT imaging for precise implant placement. From single-tooth implants to full-arch rehabilitation with All-on-4 and All-on-6, we offer comprehensive implant solutions tailored to each patient.',
      benefits: [
        'Permanent solution lasting a lifetime with proper care',
        'Preserves jawbone and prevents bone loss',
        'Looks, feels, and functions like natural teeth',
        'No adhesives or removal — fully fixed in mouth',
        'Restored confidence in eating, speaking, and smiling',
      ],
      ideal_for: [
        'Patients with one or more missing teeth',
        'Those seeking a permanent alternative to dentures',
        'Patients with sufficient jawbone density',
        'International dental tourists seeking cost-effective world-class care',
      ],
      related_technology_ids: ['cbct-scanner', 'cad-cam', 'guided-surgery'],
      related_doctor_ids: ['dr-pradeep-sharma', 'dr-ramesh-babu'],
      pricing_insight_id: 'pi-dental-implants',
      image_keyword: 'dental-implant',
      image_url: '/images/services/dental-implants.jpg',
    },
    {
      id: 'smile-design',
      name: 'Smile Design & Makeover',
      category: 'Cosmetic',
      tags: ['cosmetic', 'veneers', 'smile'],
      short_description: 'Comprehensive smile transformation combining veneers, whitening, contouring, and cosmetic bonding.',
      detailed_description: 'A complete smile makeover at FMS begins with digital smile design — a technology-driven preview of your future smile before any treatment begins. Our cosmetic dentists analyse your facial proportions, lip aesthetics, and tooth position to craft a completely personalised smile. Treatments may include porcelain veneers, teeth whitening, composite bonding, gum reshaping, and more.',
      benefits: [
        'Digital preview of your smile before treatment',
        'Combination of multiple cosmetic procedures in one plan',
        'Porcelain veneers with natural translucency',
        'Long-lasting results with proper maintenance',
        'Boost in confidence and professional appearance',
      ],
      ideal_for: [
        'Patients with stained, chipped, or misaligned teeth',
        'Those preparing for important life events',
        'International patients seeking complete aesthetic transformation',
        'Professionals wanting a high-impact smile improvement',
      ],
      related_technology_ids: ['digital-smile-design', 'cad-cam', 'laser-whitening'],
      related_doctor_ids: ['dr-kavitha-reddy', 'dr-pradeep-sharma'],
      pricing_insight_id: 'pi-smile-design',
      image_keyword: 'smile-makeover',
      image_url: '/images/services/smile-design.jpg',
    },
    {
      id: 'invisalign-aligners',
      name: 'Invisalign & Clear Aligners',
      category: 'Orthodontics',
      tags: ['orthodontics', 'aligners', 'invisalign'],
      short_description: 'Invisible braces technology for teeth straightening — no metal, no discomfort.',
      detailed_description: 'FMS Dental is a certified Invisalign provider in Hyderabad. Using a series of custom-made, virtually invisible aligners, we straighten teeth without the discomfort or aesthetic concerns of traditional metal braces. Each set of aligners moves teeth gradually, and patients typically complete treatment in 12–18 months. We also offer SureSmile and other premium clear aligner brands.',
      benefits: [
        'Nearly invisible — no one knows you are in treatment',
        'Removable for eating, brushing, and special occasions',
        'Smoother, more comfortable than metal brackets',
        'Digital tracking of progress at each appointment',
        'Suitable for teens and adults',
      ],
      ideal_for: [
        'Adults and teens seeking discreet orthodontic treatment',
        'Patients with mild to moderate alignment issues',
        'Professionals who cannot wear visible braces',
        'Those who want predictable, mapped-out treatment timelines',
      ],
      related_technology_ids: ['digital-impressions', 'itero-scanner'],
      related_doctor_ids: ['dr-anjali-mehta', 'dr-kavitha-reddy'],
      pricing_insight_id: 'pi-aligners',
      image_keyword: 'clear-aligners',
      image_url: '/images/services/invisalign-aligners.jpg',
    },
    {
      id: 'root-canal-treatment',
      name: 'Root Canal Treatment',
      category: 'Restorative',
      tags: ['root_canal', 'restorative', 'endodontics'],
      short_description: 'Painless, single-sitting root canal therapy using rotary systems and apex locators.',
      detailed_description: 'Modern root canal treatment at FMS is virtually painless and often completed in a single visit using the latest rotary endodontic systems. Our endodontists use digital apex locators and 3D imaging to ensure complete canal cleaning and precise filling. A dental crown placed after root canal therapy restores your tooth to full function.',
      benefits: [
        'Single-sitting procedure in most cases',
        'Saves natural tooth — avoids extraction',
        'Virtually painless with modern anaesthesia',
        'High success rates with microscope-assisted procedures',
        'Prevents infection spread to adjacent teeth',
      ],
      ideal_for: [
        'Patients with severe toothache or dental infection',
        'Those with deep decay reaching the pulp',
        'Cracked or fractured teeth causing sensitivity',
        'Patients wanting to save natural teeth',
      ],
      related_technology_ids: ['dental-microscope', 'apex-locator'],
      related_doctor_ids: ['dr-ramesh-babu'],
      image_keyword: 'root-canal',
      image_url: '/images/services/root-canal-treatment.jpg',
    },
    {
      id: 'laser-dentistry',
      name: 'Laser Dentistry',
      category: 'Advanced',
      tags: ['laser', 'advanced', 'gum'],
      short_description: 'Minimally invasive laser procedures for gum treatment, whitening, and cavity detection.',
      detailed_description: 'FMS Dental uses advanced soft-tissue and hard-tissue laser systems for a range of procedures — from gum contouring and depigmentation to cavity detection and teeth whitening. Laser procedures mean minimal bleeding, faster healing, and reduced need for anaesthesia in many cases.',
      benefits: [
        'Minimally invasive with minimal bleeding',
        'Faster healing compared to conventional surgery',
        'Reduced need for anaesthesia in many procedures',
        'Precise tissue removal with no damage to surrounding areas',
        'Excellent for gum reshaping and smile enhancement',
      ],
      ideal_for: [
        'Patients with gum disease (gingivitis, periodontitis)',
        'Those wanting gum contouring for aesthetic improvement',
        'Patients with gum pigmentation',
        'Those seeking advanced whitening procedures',
      ],
      related_technology_ids: ['diode-laser', 'er-yag-laser'],
      related_doctor_ids: ['dr-kavitha-reddy'],
      image_keyword: 'laser-dentistry',
      image_url: '/images/services/laser-dentistry.jpg',
    },
    {
      id: 'full-mouth-rehabilitation',
      name: 'Full Mouth Rehabilitation',
      category: 'Restorative',
      tags: ['restorative', 'implants', 'smile'],
      short_description: 'Complete restoration of severely worn, damaged, or missing dentition using crowns, implants, and prosthetics.',
      detailed_description: 'Full mouth rehabilitation at FMS addresses severe dental neglect, trauma, or congenital conditions affecting the entire bite. Using a combination of implants, crowns, bridges, veneers, and orthodontic treatment, we restore optimal function and aesthetics. This multi-disciplinary treatment is planned meticulously using digital records, study casts, and a diagnostic wax-up.',
      benefits: [
        'Comprehensive treatment planning under one roof',
        'Multi-specialist collaboration for complex cases',
        'Restoration of bite function and aesthetics simultaneously',
        'Phased treatment plans available for budget management',
        'Long-lasting results with premium materials',
      ],
      ideal_for: [
        'Patients with multiple missing or severely damaged teeth',
        'Those with bite collapse or severely worn teeth',
        'International patients seeking cost-effective total dental care',
        'Patients with sleep apnoea or TMJ disorders',
      ],
      related_technology_ids: ['cbct-scanner', 'cad-cam', 'digital-smile-design'],
      related_doctor_ids: ['dr-pradeep-sharma', 'dr-ramesh-babu', 'dr-anjali-mehta'],
      image_keyword: 'full-mouth-rehabilitation',
      image_url: '/images/services/full-mouth-rehabilitation.jpg',
    },
    {
      id: 'teeth-whitening',
      name: 'Teeth Whitening',
      category: 'Cosmetic',
      tags: ['cosmetic', 'whitening'],
      short_description: 'Professional in-office and take-home whitening systems for a noticeably brighter smile.',
      detailed_description: 'FMS Dental offers the Zoom! WhiteSpeed in-office whitening system for dramatic results in a single appointment, alongside custom take-home whitening trays for gradual whitening at your convenience. Professional whitening is significantly more effective and safer than over-the-counter products.',
      benefits: [
        'Up to 8 shades brighter in a single session',
        'Safe and supervised by dental professionals',
        'Customised trays for consistent results',
        'Long-lasting with proper maintenance',
        'Immediate confidence boost before events',
      ],
      ideal_for: [
        'Patients with stained or yellowed teeth',
        'Those preparing for weddings or special occasions',
        'Patients completing orthodontic treatment',
        'Coffee, tea, or tobacco consumers',
      ],
      related_technology_ids: ['laser-whitening', 'zoom-whitening'],
      related_doctor_ids: ['dr-kavitha-reddy'],
      pricing_insight_id: 'pi-whitening',
      image_keyword: 'teeth-whitening',
      image_url: '/images/services/teeth-whitening.jpg',
    },
    {
      id: 'porcelain-veneers',
      name: 'Porcelain Veneers',
      category: 'Cosmetic',
      tags: ['cosmetic', 'veneers', 'smile'],
      short_description: 'Ultra-thin porcelain shells bonded to teeth for an instant, dramatic smile transformation.',
      detailed_description: 'Porcelain veneers at FMS are crafted at our in-house dental lab using premium e.max and Zirconia materials. Our cosmetic dentists work closely with ceramists to ensure each veneer perfectly matches the desired shade, shape, and translucency. Minimally invasive preparation techniques preserve maximum natural tooth structure.',
      benefits: [
        'Dramatic aesthetic improvement in 2–3 visits',
        'Stain-resistant porcelain for long-lasting whiteness',
        'Corrects multiple cosmetic issues simultaneously',
        'Natural-looking with customised shape and shade',
        'Minimal tooth preparation with modern techniques',
      ],
      ideal_for: [
        'Patients with severe staining unresponsive to whitening',
        'Those with chipped, cracked, or uneven teeth',
        'Patients wanting a Hollywood smile',
        'Those with gaps between front teeth',
      ],
      related_technology_ids: ['cad-cam', 'digital-smile-design'],
      related_doctor_ids: ['dr-kavitha-reddy', 'dr-pradeep-sharma'],
      pricing_insight_id: 'pi-veneers',
      image_keyword: 'porcelain-veneers',
      image_url: '/images/services/porcelain-veneers.jpg',
    },
    {
      id: 'tmj-treatment',
      name: 'TMJ & Jaw Pain Treatment',
      category: 'Specialised',
      tags: ['tmj', 'specialised'],
      short_description: 'Comprehensive diagnosis and management of temporomandibular joint disorders and chronic jaw pain.',
      detailed_description: 'The FMS Dental TMJ clinic is one of few dedicated jaw pain centres in South India. Our specialists use advanced imaging, jaw tracking, and electromyography to accurately diagnose TMJ disorders. Treatment ranges from occlusal splints and physiotherapy to minimally invasive arthroscopy.',
      benefits: [
        'Accurate diagnosis with advanced jaw tracking technology',
        'Conservative, non-surgical treatment first approach',
        'Relief from chronic headaches associated with TMJ',
        'Customised splint therapy for bruxism',
        'Collaborative care with physiotherapists and pain specialists',
      ],
      ideal_for: [
        'Patients with jaw clicking, pain, or limited mouth opening',
        'Those suffering from chronic headaches or neck pain',
        'Patients with bruxism (teeth grinding)',
        'Those with bite misalignment causing discomfort',
      ],
      related_technology_ids: ['jaw-tracker', 'cbct-scanner'],
      related_doctor_ids: ['dr-pradeep-sharma'],
      image_keyword: 'tmj-jaw-pain',
      image_url: '/images/services/tmj-treatment.jpg',
    },
    {
      id: 'pediatric-dentistry',
      name: 'Paediatric Dentistry',
      category: 'Specialised',
      tags: ['pediatric', 'specialised', 'children'],
      short_description: 'Child-friendly dental care in a fun, anxiety-free environment by specialist paediatric dentists.',
      detailed_description: 'The FMS Kids Dental Zone is a specially designed child-friendly environment where our paediatric specialists deliver preventive and restorative care for children from infancy to 16 years. Using behaviour management techniques, nitrous oxide sedation, and a welcoming atmosphere, we ensure positive dental experiences for children.',
      benefits: [
        'Dedicated child-friendly clinic environment',
        'Specialist paediatric dentists with child behaviour training',
        'Preventive treatments — sealants, fluoride, space maintainers',
        'Anxiety management including nitrous oxide',
        'Building positive dental habits from an early age',
      ],
      ideal_for: [
        'Children aged 1–16 years',
        'Kids with dental anxiety or special needs',
        'Parents wanting preventive dental care for children',
        'Families seeking routine check-ups and cleanings',
      ],
      related_technology_ids: ['digital-x-ray'],
      related_doctor_ids: ['dr-sunita-verma'],
      image_keyword: 'pediatric-dentistry',
      image_url: '/images/services/pediatric-dentistry.jpg',
    },
  ],

  clinics_and_locations: [
    {
      id: 'jubilee-hills',
      branch_name: 'FMS Dental — Jubilee Hills',
      city: 'Hyderabad',
      area: 'Jubilee Hills',
      address: 'Plot No. 1241, Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033',
      landmarks: ['Near Jubilee Hills Checkpost', 'Opposite Ohri\'s Restaurant', 'Adjacent to Road No. 36 Park'],
      phone_numbers: ['+91 40 4343 5540', '+91 98480 12345'],
      email: 'jubileehills@fmsdental.com',
      hours: 'Mon–Sat: 9:00 AM – 7:00 PM | Sun: 10:00 AM – 2:00 PM',
      special_focus: 'International Dental Centre',
    },
    {
      id: 'kondapur',
      branch_name: 'FMS Dental — Kondapur',
      city: 'Hyderabad',
      area: 'Kondapur',
      address: 'Plot 14, Rd 4, Kondapur, Hyderabad, Telangana 500084',
      landmarks: ['Near Inorbit Mall', 'Opposite ICICI Bank Kondapur', '5 min from HITEC City'],
      phone_numbers: ['+91 40 4343 5541', '+91 98480 23456'],
      email: 'kondapur@fmsdental.com',
      hours: 'Mon–Sat: 9:00 AM – 8:00 PM | Sun: Closed',
      special_focus: 'Implant Centre',
    },
    {
      id: 'dilsukhnagar',
      branch_name: 'FMS Dental — Dilsukhnagar',
      city: 'Hyderabad',
      area: 'Dilsukhnagar',
      address: '5-9-22, Ramakrishna Theatre Road, Dilsukhnagar, Hyderabad, Telangana 500060',
      landmarks: ['Near Ramakrishna Theatre', 'Opposite Reliance Fresh', 'Close to Dilsukhnagar Metro Station'],
      phone_numbers: ['+91 40 4343 5542', '+91 98480 34567'],
      email: 'dilsukhnagar@fmsdental.com',
      hours: 'Mon–Sat: 9:00 AM – 7:30 PM | Sun: 10:00 AM – 2:00 PM',
    },
    {
      id: 'miyapur',
      branch_name: 'FMS Dental — Miyapur',
      city: 'Hyderabad',
      area: 'Miyapur',
      address: '202, Mythri Nagar, Miyapur, Hyderabad, Telangana 500049',
      landmarks: ['Near Miyapur Bus Depot', 'Opposite Apollo Pharmacy', 'Close to Miyapur Metro Station'],
      phone_numbers: ['+91 40 4343 5543', '+91 98480 45678'],
      email: 'miyapur@fmsdental.com',
      hours: 'Mon–Sat: 9:00 AM – 7:30 PM | Sun: Closed',
    },
    {
      id: 'kukatpally',
      branch_name: 'FMS Dental — Kukatpally',
      city: 'Hyderabad',
      area: 'Kukatpally',
      address: 'Plot 78, KPHB Colony, Kukatpally, Hyderabad, Telangana 500072',
      landmarks: ['Near KPHB Colony Phase 3', 'Opposite Jyothi Hospital', 'Close to Moosapet Metro Station'],
      phone_numbers: ['+91 40 4343 5544', '+91 98480 56789'],
      email: 'kukatpally@fmsdental.com',
      hours: 'Mon–Sat: 9:00 AM – 7:30 PM | Sun: 10:00 AM – 1:00 PM',
    },
    {
      id: 'secunderabad',
      branch_name: 'FMS Dental — Secunderabad',
      city: 'Hyderabad',
      area: 'Secunderabad',
      address: 'S-2, Ground Floor, SD Plaza, MG Road, Secunderabad, Telangana 500003',
      landmarks: ['Near Paradise Circle', 'Opposite Parade Grounds', '2 min from Secunderabad Railway Station'],
      phone_numbers: ['+91 40 4343 5545', '+91 98480 67890'],
      email: 'secunderabad@fmsdental.com',
      hours: 'Mon–Sat: 9:00 AM – 7:00 PM | Sun: 10:00 AM – 2:00 PM',
      special_focus: 'Smile Design Studio',
    },
  ],

  doctors_and_specialists: [
    {
      id: 'dr-pradeep-sharma',
      name: 'Dr. Pradeep Sharma',
      designation: 'Chief Implantologist & Oral Surgeon',
      specialties: ['Dental Implants', 'Oral Surgery', 'Full Mouth Rehabilitation', 'TMJ Treatment'],
      experience_years: 22,
      clinic_ids: ['jubilee-hills', 'kondapur'],
      bio: 'Dr. Pradeep Sharma is a fellowship-trained implantologist with over 22 years of experience and 15,000+ successful implant procedures. He trained at NYU College of Dentistry and holds an MDS in Oral Surgery. Known for complex full-arch rehabilitations and All-on-4 procedures.',
      image_seed: 'pradeep-sharma-dentist',
      qualifications: ['BDS, Osmania University', 'MDS – Oral Surgery, AIIMS Delhi', 'Fellowship in Implantology, NYU'],
      image_url: '/images/doctors/dr-pradeep-sharma.jpg',
    },
    {
      id: 'dr-kavitha-reddy',
      name: 'Dr. Kavitha Reddy',
      designation: 'Senior Cosmetic & Aesthetic Dentist',
      specialties: ['Smile Design', 'Porcelain Veneers', 'Teeth Whitening', 'Laser Dentistry'],
      experience_years: 16,
      clinic_ids: ['jubilee-hills', 'secunderabad'],
      bio: 'Dr. Kavitha Reddy is one of Hyderabad\'s most sought-after cosmetic dentists, specialising in digital smile design and smile makeovers. She is a certified Zoom! Whitening provider and has completed advanced training in aesthetic dentistry at the Eastman Dental Institute, London.',
      image_seed: 'kavitha-reddy-dentist',
      qualifications: ['BDS, Kakatiya University', 'MDS – Conservative Dentistry', 'Advanced Aesthetics, Eastman Dental Institute London'],
      image_url: '/images/doctors/dr-kavitha-reddy.jpg',
    },
    {
      id: 'dr-anjali-mehta',
      name: 'Dr. Anjali Mehta',
      designation: 'Consultant Orthodontist',
      specialties: ['Invisalign', 'Clear Aligners', 'Braces', 'Orthognathic Surgery Coordination'],
      experience_years: 14,
      clinic_ids: ['jubilee-hills', 'kondapur', 'kukatpally'],
      bio: 'Dr. Anjali Mehta is a Diamond Invisalign provider and has completed over 800 aligner cases. Her expertise spans from simple crowding corrections to complex skeletal discrepancy cases. She completed her MDS from NIMHANS and has additional training in SureSmile and OrthoCAD.',
      image_seed: 'anjali-mehta-ortho',
      qualifications: ['BDS, Rajiv Gandhi University', 'MDS – Orthodontics', 'Diamond Invisalign Provider Certification'],
      image_url: '/images/doctors/dr-anjali-mehta.jpg',
    },
    {
      id: 'dr-ramesh-babu',
      name: 'Dr. Ramesh Babu',
      designation: 'Endodontist & Restorative Specialist',
      specialties: ['Root Canal Treatment', 'Dental Implants', 'Crowns & Bridges', 'Microscope Dentistry'],
      experience_years: 18,
      clinic_ids: ['dilsukhnagar', 'jubilee-hills'],
      bio: 'Dr. Ramesh Babu is a highly experienced endodontist known for painless single-sitting root canal procedures using the latest rotary systems. He is one of the few dentists in Hyderabad trained in microscope-assisted endodontics, ensuring the highest precision in complex cases.',
      image_seed: 'ramesh-babu-endo',
      qualifications: ['BDS, NTR Health University', 'MDS – Conservative Dentistry & Endodontics', 'Microscope Endodontics Certification, WaveOne Gold'],
      image_url: '/images/doctors/dr-ramesh-babu.jpg',
    },
    {
      id: 'dr-sunita-verma',
      name: 'Dr. Sunita Verma',
      designation: 'Paediatric Dentist',
      specialties: ['Paediatric Dentistry', 'Child Behaviour Management', 'Preventive Dentistry', 'Special Needs Dentistry'],
      experience_years: 11,
      clinic_ids: ['miyapur', 'kukatpally'],
      bio: 'Dr. Sunita Verma is passionate about creating positive first dental experiences for children. With 11 years of specialised paediatric dentistry practice, she has treated thousands of children, including those with autism and special needs, using advanced behaviour management techniques.',
      image_seed: 'sunita-verma-pediatric',
      qualifications: ['BDS, Manipal University', 'MDS – Paediatric Dentistry', 'Certification in Special Needs Dentistry'],
      image_url: '/images/doctors/dr-sunita-verma.jpg',
    },
    {
      id: 'dr-venkat-narayan',
      name: 'Dr. Venkat Narayan',
      designation: 'Periodontist & Implant Surgeon',
      specialties: ['Gum Disease Treatment', 'Bone Grafting', 'Sinus Lift', 'Implants'],
      experience_years: 13,
      clinic_ids: ['kondapur', 'secunderabad'],
      bio: 'Dr. Venkat Narayan is a periodontist with extensive training in regenerative procedures. He specialises in complex bone grafting, sinus lift augmentation, and gum surgeries that create ideal foundations for implants, even in compromised cases.',
      image_seed: 'venkat-narayan-perio',
      qualifications: ['BDS, Andhra University', 'MDS – Periodontics', 'ITI Scholar – Implant Dentistry, Switzerland'],
      image_url: '/images/doctors/dr-venkat-narayan.jpg',
    },
  ],

  technology_and_facilities: [
    {
      id: 'cbct-scanner',
      name: '3D Cone Beam CT Scanner',
      category: 'Imaging',
      description: 'Full 3D imaging of teeth, jaw, and surrounding structures for precise implant planning and surgical guides.',
      benefit: 'Eliminates guesswork in implant placement; surgical accuracy within 0.2mm',
    },
    {
      id: 'cad-cam',
      name: 'CAD/CAM Milling Unit',
      category: 'Restorative',
      description: 'Computer-aided design and manufacturing for same-day crowns, veneers, and prosthetics from premium ceramic blocks.',
      benefit: 'Same-day restorations in many cases; eliminates temporary teeth',
    },
    {
      id: 'digital-smile-design',
      name: 'Digital Smile Design (DSD)',
      category: 'Cosmetic',
      description: 'Digital facial analysis and smile preview technology — see your future smile before treatment begins.',
      benefit: 'Patient sees the result before committing to any procedure',
    },
    {
      id: 'diode-laser',
      name: 'Diode Laser System',
      category: 'Laser',
      description: 'Soft-tissue diode laser for gum contouring, depigmentation, and frenectomy with minimal bleeding.',
      benefit: 'Suture-free procedures with faster healing and minimal discomfort',
    },
    {
      id: 'dental-microscope',
      name: 'Surgical Operating Microscope',
      category: 'Precision',
      description: 'High-magnification microscope for ultra-precise root canal and restorative procedures.',
      benefit: 'Detects issues invisible to the naked eye; eliminates missed canals',
    },
    {
      id: 'digital-impressions',
      name: 'Digital Impression System',
      category: 'Orthodontics',
      description: 'Intraoral scanner for comfortable, accurate impressions without traditional putty trays.',
      benefit: 'No gagging; digital files sent instantly to lab for faster results',
    },
    {
      id: 'itero-scanner',
      name: 'iTero Element Scanner',
      category: 'Orthodontics',
      description: 'Invisalign\'s own digital scanner for highly accurate aligner treatment planning.',
      benefit: 'Outcome Simulator shows predicted tooth movement before treatment',
    },
    {
      id: 'guided-surgery',
      name: 'Computer-Guided Implant Surgery',
      category: 'Implants',
      description: 'Pre-planned implant placement using digital surgical guides fabricated from CBCT data.',
      benefit: 'Flapless surgery possible in eligible patients; minimal downtime',
    },
  ],

  awards_and_recognitions: [
    {
      id: 'nabh',
      name: 'NABH Accreditation',
      year: '2019',
      issuer: 'National Accreditation Board for Hospitals & Healthcare Providers',
      description: 'FMS Dental is NABH-accredited, ensuring the highest standards of patient safety, hygiene, and clinical protocols.',
    },
    {
      id: 'gcr-2023',
      name: 'Global Clinic Rating — Top 10 Dental Clinic India',
      year: '2023',
      issuer: 'Global Clinic Rating (GCR)',
      description: 'Ranked among the Top 10 dental clinics in India by the Global Clinic Rating platform used by international dental tourists.',
    },
    {
      id: 'dental-tourism',
      name: 'Best Dental Tourism Destination — Hyderabad',
      year: '2022',
      issuer: 'India Medical Tourism Council',
      description: 'Recognised as the top dental destination for international patients visiting Hyderabad for affordable, world-class care.',
    },
    {
      id: 'excellence-award',
      name: 'Excellence in Cosmetic Dentistry Award',
      year: '2021',
      issuer: 'Indian Dental Association — Telangana Chapter',
      description: 'Awarded for outstanding contributions to cosmetic and aesthetic dentistry in Telangana.',
    },
  ],

  testimonials_and_reviews: [
    {
      id: 'test-1',
      patient_name: 'Arjun Mehrotra',
      location: 'Banjara Hills, Hyderabad',
      treatment: 'Dental Implants (Full Arch)',
      rating: 5,
      review: 'After losing most of my upper teeth in an accident, I was devastated. Dr. Pradeep and the FMS team gave me back my smile and my confidence in 4 months. The All-on-4 implants look completely natural. Worth every rupee.',
      date: 'February 2024',
      image_seed: 'arjun-mehrotra-patient',
      image_url: '/images/testimonials/test-1.jpg',
    },
    {
      id: 'test-2',
      patient_name: 'Priya Raghunathan',
      location: 'Dubai, UAE',
      treatment: 'Smile Makeover — Veneers + Whitening',
      rating: 5,
      review: 'I flew in from Dubai specifically for my smile makeover at FMS Jubilee Hills. The quality of porcelain veneers is on par with anything I have seen in Europe, and the cost was a fraction. Dr. Kavitha is a true artist.',
      date: 'January 2024',
      image_seed: 'priya-raghunathan-uae',
      image_url: '/images/testimonials/test-2.jpg',
    },
    {
      id: 'test-3',
      patient_name: 'Srinivas Goud',
      location: 'Dilsukhnagar, Hyderabad',
      treatment: 'Root Canal Treatment',
      rating: 5,
      review: 'I had been avoiding the dentist for years due to fear. Dr. Ramesh made the entire root canal completely painless — I barely felt anything. The single-sitting procedure was done in 90 minutes. Wish I had come sooner.',
      date: 'March 2024',
      image_seed: 'srinivas-goud-patient',
      image_url: '/images/testimonials/test-3.jpg',
    },
    {
      id: 'test-4',
      patient_name: 'Fatima Al-Rashidi',
      location: 'Oman',
      treatment: 'Invisalign + Smile Design',
      rating: 5,
      review: 'FMS Dental is worth the trip from Oman. My Invisalign treatment was planned meticulously and the results after 14 months exceeded my expectations. Highly professional team, excellent English communication, and the clinic is spotlessly clean.',
      date: 'December 2023',
      image_seed: 'fatima-oman-patient',
      image_url: '/images/testimonials/test-4.jpg',
    },
    {
      id: 'test-5',
      patient_name: 'Rohan Kapoor',
      location: 'Kondapur, Hyderabad',
      treatment: 'Paediatric Dentistry',
      rating: 5,
      review: 'My 7-year-old used to cry just at the mention of the dentist. Dr. Sunita is magical — my son actually looks forward to his appointments now. The kids zone is fantastic and the approach is so gentle.',
      date: 'April 2024',
      image_seed: 'rohan-kapoor-parent',
      image_url: '/images/testimonials/test-5.jpg',
    },
    {
      id: 'test-6',
      patient_name: 'Vijayalaxmi Desai',
      location: 'Secunderabad, Hyderabad',
      treatment: 'Full Mouth Rehabilitation',
      rating: 5,
      review: 'I had neglected my teeth for decades. The multi-specialist team at FMS created a comprehensive plan and restored my entire mouth. The transformation took 8 months but the result is beyond anything I imagined. Life-changing.',
      date: 'November 2023',
      image_seed: 'vijayalaxmi-secunderabad',
      image_url: '/images/testimonials/test-6.jpg',
    },
    {
      id: 'test-7',
      patient_name: 'James Fernandez',
      location: 'Goa',
      treatment: 'Dental Implants + Crowns',
      rating: 5,
      review: 'Travelled to Hyderabad for implants after my dentist in Goa quoted 3x the price. FMS\'s work quality is outstanding — the consultation, CBCT scan, and surgery were all seamlessly coordinated. Stayed at a hotel nearby and the whole trip was worth it.',
      date: 'October 2023',
      image_seed: 'james-fernandez-goa',
      image_url: '/images/testimonials/test-7.jpg',
    },
    {
      id: 'test-8',
      patient_name: 'Meena Krishnamurthy',
      location: 'Jubilee Hills, Hyderabad',
      treatment: 'Laser Gum Treatment',
      rating: 5,
      review: 'Had been struggling with bleeding gums for years. The laser gum treatment at FMS was a revelation — no stitches, minimal discomfort, and my gums are completely healthy now after just two sessions. Dr. Venkat is exceptional.',
      date: 'May 2024',
      image_seed: 'meena-krishnamurthy',
      image_url: '/images/testimonials/test-8.jpg',
    },
  ],

  pricing_insights: [
    {
      id: 'pi-dental-implants',
      service_id: 'dental-implants',
      treatment_name: 'Single Dental Implant (Titanium + Crown)',
      india_range: '₹25,000 – ₹60,000',
      global_range: '$3,000 – $6,000 (USA/UK)',
      savings_note: 'Save 60–80% vs USA/UK prices without compromising on quality',
      disclaimer: 'Prices vary based on implant brand, bone condition, and complexity. Final quote provided after examination.',
    },
    {
      id: 'pi-smile-design',
      service_id: 'smile-design',
      treatment_name: 'Complete Smile Makeover (8 Veneers + Whitening)',
      india_range: '₹1,50,000 – ₹3,50,000',
      global_range: '$15,000 – $30,000 (USA/UK)',
      savings_note: 'Comprehensive smile transformation at a fraction of international costs',
      disclaimer: 'Price depends on number of veneers, material choice, and additional procedures.',
    },
    {
      id: 'pi-aligners',
      service_id: 'invisalign-aligners',
      treatment_name: 'Invisalign Comprehensive',
      india_range: '₹1,20,000 – ₹2,50,000',
      global_range: '$5,000 – $9,000 (USA)',
      savings_note: 'Certified Invisalign Diamond Provider at significantly lower cost',
      disclaimer: 'Price based on case complexity and number of aligners required.',
    },
    {
      id: 'pi-veneers',
      service_id: 'porcelain-veneers',
      treatment_name: 'Per Porcelain Veneer (e.max)',
      india_range: '₹18,000 – ₹30,000 per tooth',
      global_range: '$1,500 – $2,500 per tooth (USA)',
      savings_note: 'Premium e.max veneers at 70% savings vs international prices',
      disclaimer: 'Cost per veneer varies based on material (e.max vs zirconia) and case complexity.',
    },
    {
      id: 'pi-whitening',
      service_id: 'teeth-whitening',
      treatment_name: 'In-Office Zoom! Whitening',
      india_range: '₹8,000 – ₹15,000',
      global_range: '$500 – $1,000 (USA)',
      savings_note: 'Same Zoom! technology used globally at a fraction of the cost',
      disclaimer: 'Results vary based on initial tooth shade and lifestyle factors.',
    },
  ],

  contact_and_appointment_info: {
    primary_phone: '+91 40 4343 5540',
    secondary_phone: '+91 98480 12345',
    email: 'appointments@fmsdental.com',
    whatsapp: '+91 98480 12345',
    booking_hours: 'Mon–Sat: 9:00 AM – 7:00 PM | Sun: 10:00 AM – 2:00 PM',
    time_slots: [
      { id: 'slot-1', label: '9:00 AM – 10:00 AM', value: '09:00' },
      { id: 'slot-2', label: '10:00 AM – 11:00 AM', value: '10:00' },
      { id: 'slot-3', label: '11:00 AM – 12:00 PM', value: '11:00' },
      { id: 'slot-4', label: '12:00 PM – 1:00 PM', value: '12:00' },
      { id: 'slot-5', label: '2:00 PM – 3:00 PM', value: '14:00' },
      { id: 'slot-6', label: '3:00 PM – 4:00 PM', value: '15:00' },
      { id: 'slot-7', label: '4:00 PM – 5:00 PM', value: '16:00' },
      { id: 'slot-8', label: '5:00 PM – 6:00 PM', value: '17:00' },
      { id: 'slot-9', label: '6:00 PM – 7:00 PM', value: '18:00' },
    ],
  },

  tagging_dimensions: {
    treatment_tags: [
      { id: 'implants', label: 'Dental Implants', icon: 'Tooth' },
      { id: 'cosmetic', label: 'Cosmetic Dentistry', icon: 'Sparkle' },
      { id: 'orthodontics', label: 'Orthodontics', icon: 'AlignLeft' },
      { id: 'root_canal', label: 'Root Canal', icon: 'FirstAid' },
      { id: 'tmj', label: 'TMJ & Jaw Pain', icon: 'Smiley' },
      { id: 'veneers', label: 'Veneers', icon: 'Star' },
      { id: 'aligners', label: 'Clear Aligners', icon: 'Shapes' },
      { id: 'laser', label: 'Laser Dentistry', icon: 'Lightning' },
      { id: 'whitening', label: 'Teeth Whitening', icon: 'SunHorizon' },
      { id: 'pediatric', label: 'Kids Dentistry', icon: 'Baby' },
    ],
    specialty_tags: [
      'Implantology',
      'Cosmetic Dentistry',
      'Orthodontics',
      'Endodontics',
      'Periodontics',
      'Paediatric Dentistry',
      'Oral Surgery',
    ],
    city_tags: ['Jubilee Hills', 'Kondapur', 'Dilsukhnagar', 'Miyapur', 'Kukatpally', 'Secunderabad'],
  },
};

export default fmsData;
